---
-  hosts: all
   become: yes
   tasks:
   -  name: install jdk
      apt: name=default-jdk state=present

   -  name: create tomcat group
      group:
        name: tomcat

   -  name: create usr and add to group
      user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat

   -  name: create tomcat folder inside
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: 0755

   -  name: download packge
      unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]

   -  name: change permisiiosns
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 0777
        recurse: yes
        state: directory

   -  name: copy tomcat service file
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/

   -  name: deamon-reload
      systemd:
        name: tomcat
        state: started
        daemon_reload: true     
