---
-  name: install jdk
   apt: name=default-jdk state=present

-  name: create tomcat group
   group:
     name: tomcat

-  name: create usr and add to group
   user:
     name: tomcat
     group: tomcat
     home: /usr/share/tomcat

-  name: create tomcat folder inside
   file:
     path: /opt/tomcat
     state: directory
     owner: tomcat
     group: tomcat
     mode: 0755

-  name: download packge
   unarchive:
     src: https://downloads.apache.org/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz
     dest: /opt/tomcat
     remote_src: yes
     extra_opts: [--strip-components=1]

-  name: change permisiiosns
   file:
     path: /opt/tomcat
     owner: tomcat
     group: tomcat
     mode: 0777
     recurse: yes
     state: directory

-  name: copy tomcat service file
   template:
     src: tomcat.service
     dest: /etc/systemd/system/

-  name: deamon-reload
   systemd:
     name: tomcat
     state: started
     daemon_reload: true     
-  name: copy user.xml
   template:
     src: tomcat-users.xml
     dest: /opt/tomcat/conf
     owner: tomcat
     group: tomcat
     mode: 0777
     
-  name: copy backup.sh
   template:
     src: backup.sh
     dest: /opt
     mode: 0777
      
-  name: copy deploy.sh
   template:
     src: deploy.sh
     dest: /opt
     mode: 0777
      
-  name: excute backup script
   shell: sh /opt/backup.sh
    
-  name: excute deploy.sh
   shell: sh /opt/deploy.sh
